### ISSUE TITLE
[BUG/ISSUE] Client crash when building beacon on version 1.18.2-1.0.0

### ISSUE THREAD

**Issue by daniele-bondi** [CERBON-MODS/CERBONs-Better-Beacons#13]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] ~~**I have checked that I am running the latest version of Better Beacons Mod**~~ I am running version 1.0.0
- [x] **I have checked the [FAQ](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/blob/master/CODE_OF_CONDUCT.md)**

## Loader, loader version and minecraft version
`Forge 40.2.9`, `Minecraft 1.18.2`

## Describe the bug
The client crashed after I build a beacon. I believe it crashed when the beam started coming out of the beacon block, but I'm not sure because I wasn't really paying attention.
The server is running ok, but trying to rejoin the server makes the game crash after terrain loading.

## To reproduce
1. Build a level 4 beacon base with iron blocks (10x10 base).
2. Place 4 beacons on top.

## Expected behavior
No crash.

## Screenshots
N/A

## Latest log
The entire log file is too long, so I posted the last few lines with the stack trace of the fatal error.

<details>

```
[01Mar2024 14:00:22.257] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/cable
[01Mar2024 14:00:22.257] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/variable_transformer_input
[01Mar2024 14:00:22.257] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/variable_transformer_output
[01Mar2024 14:00:22.257] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/part_static_light_panel
[01Mar2024 14:00:22.257] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/part_display_panel
[01Mar2024 14:00:22.257] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_programmer
[01Mar2024 14:00:22.258] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_programmer_to_portable
[01Mar2024 14:00:22.258] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_programmer_from_portable
[01Mar2024 14:00:22.258] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/variablestore
[01Mar2024 14:00:22.258] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/materializer
[01Mar2024 14:00:22.258] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/proxy
[01Mar2024 14:00:22.260] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/cable
[01Mar2024 14:00:22.261] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.logic.variables from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/variable_transformer_input
[01Mar2024 14:00:22.261] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.logic.variables from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/variable_transformer_output
[01Mar2024 14:00:22.261] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.logic.variables from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_director
[01Mar2024 14:00:22.261] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.logic.variables from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/variablestore
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.parts.other from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/part_static_light_panel
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.parts.other from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/part_display_panel
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.parts.other from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:special/part_connector_omni_directional
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.parts.other from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:special/part_connector_omni_directional_copy
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.parts.other from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:special/part_connector_omni_directional_join
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/materializer
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/proxy
[01Mar2024 14:00:22.263] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/delay
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/energy_battery
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/coal_generator
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/mechanical_squeezer
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual.machines from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/mechanical_drying_basin
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_programmer
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_programmer_to_portable
[01Mar2024 14:00:22.264] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integrateddynamics.manual from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integrateddynamics:crafting/logic_programmer_from_portable
[01Mar2024 14:00:22.271] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedterminals.storage_terminal from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedterminals:crafting/part_terminal_storage
[01Mar2024 14:00:22.271] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedterminals.storage_terminal from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedterminals:crafting/terminal_storage_portable
[01Mar2024 14:00:22.271] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedterminals.section.main from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedterminals:crafting/part_terminal_crafting_job
[01Mar2024 14:00:22.275] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_exporter_world_item
[01Mar2024 14:00:22.275] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_importer_world_item
[01Mar2024 14:00:22.275] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_exporter_world_fluid
[01Mar2024 14:00:22.275] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_importer_world_fluid
[01Mar2024 14:00:22.275] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_exporter_world_energy
[01Mar2024 14:00:22.275] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_importer_world_energy
[01Mar2024 14:00:22.276] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_exporter_world_block
[01Mar2024 14:00:22.276] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.world from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_importer_world_block
[01Mar2024 14:00:22.276] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.section.main from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_player_simulator
[01Mar2024 14:00:22.279] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedterminals.section.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedterminals:crafting/part_terminal_storage
[01Mar2024 14:00:22.283] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.section.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_exporter_world_item
[01Mar2024 14:00:22.283] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.section.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_importer_world_item
[01Mar2024 14:00:22.283] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.section.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_exporter_world_block
[01Mar2024 14:00:22.283] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.section.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_importer_world_block
[01Mar2024 14:00:22.283] [Render thread/WARN] [integrateddynamics/]: Invalid appendix info_book.integratedtunnels.section.tutorials from mod integrateddynamics in an infobook: Could not find minecraft:crafting recipe for integratedtunnels:crafting/part_player_simulator
[01Mar2024 14:00:22.310] [Render thread/INFO] [mezz.jei.common.ingredients.IngredientManager/]: Ingredients are being removed at runtime: 39 net.minecraft.world.item.ItemStack
[01Mar2024 14:00:23.324] [Render thread/INFO] [configured/]: Unloading synced configs from server
[01Mar2024 14:00:23.324] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedOutEvent
[01Mar2024 14:00:23.324] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[01Mar2024 14:00:23.324] [Render thread/INFO] [mezz.jei.forge.startup.ClientLifecycleHandler/]: Stopping JEI
[01Mar2024 14:00:23.545] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[01Mar2024 14:00:23.842] [Finalizer/WARN] [ModernFix/]: One or more BufferBuilders have been leaked, ModernFix will attempt to correct this.
[01Mar2024 14:00:23.841] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:691) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:208) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1693) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2352!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-1.5.8-prism.jar:1.5.8-prism]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1599) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?]
	at java.util.Collections.min(Collections.java:601) ~[?:?]
	at com.cerbon.better_beacons.util.json.BeaconBaseBlocksAmplifierManager.getLowestAmplifier(BeaconBaseBlocksAmplifierManager.java:79) ~[CerbonsBetterBeacons-Forge-1.18.2-1.0.0.jar%2381!/:1.0.0]
	at net.minecraft.world.level.block.entity.BeaconBlockEntity.handler$egj000$better_beacons_makeBeaconBaseGoesTillLevelFiveAndChangeAmplifierBasedOnTheBeaconBaseBlock(BeaconBlockEntity.java:1248) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.world.level.block.entity.BeaconBlockEntity.m_155092_(BeaconBlockEntity.java) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.world.level.block.entity.BeaconBlockEntity.m_155107_(BeaconBlockEntity.java:150) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%23259!/:?]
	... 28 more
[01Mar2024 14:00:23.849] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID e47675a3-2f02-4466-84a1-1b8028212702
[01Mar2024 14:00:23.855] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 8639a428-5adc-4526-bdd9-22267a13b856
[01Mar2024 14:00:23.856] [Thread-5/INFO] [FancyVideo-API/]: Running FancyVideo-API shutdown hook
[01Mar2024 14:00:23.856] [Thread-5/INFO] [FancyVideo-API/]: Running shutdown
[01Mar2024 14:00:23.856] [Thread-5/INFO] [FancyVideo-API/]: Running shutdown step 1 finished
[01Mar2024 14:00:23.856] [Thread-5/INFO] [FancyVideo-API/]: Running shutdown step 2 finished
[01Mar2024 14:00:23.857] [Thread-5/INFO] [FancyVideo-API/]: Running shutdown completely finished
[01Mar2024 14:00:23.857] [Thread-5/INFO] [FancyVideo-API/]: Shutdown hook finished
```

</details>

## Additional context
I don't think it's relevant but I added this mod to the Create Arcane Engineering modpack.

**Comment by CerbonXD** [comment]
The 1.18.2 version is an alpha file and I was never able to make the mod work on 1.18 correctly. I also won't give support for this version. Sorry about it.
